// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtYmsrulMe1JeH-Drh4xCLD5xX2xvFIEM',
    appId: '1:839582223882:web:b63ae3a496717a7a6559f3',
    messagingSenderId: '839582223882',
    projectId: 'chat1-7266e',
    authDomain: 'chat1-7266e.firebaseapp.com',
    storageBucket: 'chat1-7266e.appspot.com',
    measurementId: 'G-Z1L8L78B8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9bT36I-g14_SrwL3Fn7F1gxbiizKT9r8',
    appId: '1:839582223882:android:c91eeb562a0a89356559f3',
    messagingSenderId: '839582223882',
    projectId: 'chat1-7266e',
    storageBucket: 'chat1-7266e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0N6ZaXjTSLPSLH0GPgR0V4OJCXxUWjZg',
    appId: '1:839582223882:ios:4a13e2e98bd075046559f3',
    messagingSenderId: '839582223882',
    projectId: 'chat1-7266e',
    storageBucket: 'chat1-7266e.appspot.com',
    iosBundleId: 'com.example.chat1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0N6ZaXjTSLPSLH0GPgR0V4OJCXxUWjZg',
    appId: '1:839582223882:ios:4a13e2e98bd075046559f3',
    messagingSenderId: '839582223882',
    projectId: 'chat1-7266e',
    storageBucket: 'chat1-7266e.appspot.com',
    iosBundleId: 'com.example.chat1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtYmsrulMe1JeH-Drh4xCLD5xX2xvFIEM',
    appId: '1:839582223882:web:f7f9e44f35b1f5586559f3',
    messagingSenderId: '839582223882',
    projectId: 'chat1-7266e',
    authDomain: 'chat1-7266e.firebaseapp.com',
    storageBucket: 'chat1-7266e.appspot.com',
    measurementId: 'G-MF3G0L0ZPL',
  );
}
